import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Piano_Music_Staff_Group',
                'Piano_Music_RH_Staff',
                'RH_Voice_I',
                'RH_Rest_Voice_I',
                'RH_Voice_I_Inserts',
                'RH_Voice_II',
                'RH_Voice_II_Inserts',
                'RH_Voice_III',
                'RH_Voice_III_Inserts',
                'RH_Voice_IV',
                'RH_Voice_IV_Inserts',
                'RH_Voice_V',
                'RH_Rest_Voice_V',
                'RH_Voice_VI',
                'RH_Resonance_Voice',
                'Piano_Music_LH_Staff',
                'LH_Voice_I',
                'LH_Voice_II',
                'LH_Rest_Voice_II',
                'LH_Voice_III',
                'LH_Voice_IV',
                'LH_Rest_Voice_IV',
                'LH_Voice_IV_Inserts',
                'LH_Voice_V',
                'LH_Rest_Voice_V',
                'LH_Voice_V_Inserts',
                'LH_Rest_Voice_V_Inserts',
                'LH_Voice_VI',
                'LH_Voice_VI_Inserts',
                'LH_Resonance_Voice',
                'LH_Resonance_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [34, 40, 47, 55, 61, 68, 71, 76],
            ),
        ('duration', "1'54''"),
        (
            'fermata_measure_numbers',
            [54],
            ),
        ('final_measure_number', 77),
        ('first_measure_number', 34),
        ('segment_name', 'C'),
        ('segment_number', 4),
        ('start_clock_time', "1'09''"),
        ('stop_clock_time', "3'03''"),
        (
            'time_signatures',
            [
                '6/4',
                '3/4',
                '6/4',
                '9/8',
                '3/4',
                '6/4',
                '3/4',
                '3/4',
                '5/4',
                '4/4',
                '5/4',
                '3/4',
                '5/4',
                '4/4',
                '5/4',
                '4/4',
                '1/4',
                '7/8',
                '4/4',
                '2/4',
                '1/4',
                '2/4',
                '4/4',
                '2/4',
                '4/4',
                '3/4',
                '5/8',
                '2/4',
                '3/4',
                '2/4',
                '5/8',
                '1/4',
                '7/4',
                '6/4',
                '4/4',
                '4/4',
                '6/4',
                '4/4',
                '2/4',
                '4/4',
                '4/4',
                '4/4',
                '6/4',
                '16/4',
                ],
            ),
        ]
    )
