import abjad


metadata = abjad.OrderedDict(
    [
        (
            'bol_measure_numbers',
            [34, 40, 47, 55, 61, 68, 71, 76],
            ),
        ('duration', "1'56''"),
        (
            'fermata_measure_numbers',
            [54],
            ),
        ('final_measure_number', 77),
        ('first_measure_number', 34),
        ('segment_name', 'C'),
        ('segment_number', 4),
        ('start_clock_time', "1'14''"),
        ('stop_clock_time', "3'10''"),
        (
            'time_signatures',
            [
                '6/4',
                '3/4',
                '6/4',
                '9/8',
                '3/4',
                '6/4',
                '3/4',
                '3/4',
                '5/4',
                '4/4',
                '5/4',
                '3/4',
                '5/4',
                '4/4',
                '5/4',
                '4/4',
                '1/4',
                '7/8',
                '4/4',
                '2/4',
                '1/4',
                '2/4',
                '4/4',
                '2/4',
                '4/4',
                '3/4',
                '5/8',
                '2/4',
                '3/4',
                '2/4',
                '5/8',
                '1/4',
                '7/4',
                '6/4',
                '4/4',
                '4/4',
                '6/4',
                '4/4',
                '2/4',
                '4/4',
                '4/4',
                '4/4',
                '6/4',
                '16/4',
                ],
            ),
        ]
    )
