import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Piano_Music_Staff_Group',
                'Piano_Music_RH_Staff',
                'RH_Voice_I',
                'RH_Rest_Voice_I',
                'RH_Voice_I_Inserts',
                'RH_Voice_II',
                'RH_Voice_II_Inserts',
                'RH_Voice_III',
                'RH_Rest_Voice_III',
                'RH_Voice_III_Inserts',
                'RH_Voice_IV',
                'RH_Voice_IV_Inserts',
                'RH_Voice_V',
                'RH_Voice_VI',
                'RH_Resonance_Voice',
                'Piano_Music_LH_Staff',
                'LH_Voice_I',
                'LH_Voice_II',
                'LH_Voice_III',
                'LH_Voice_IV',
                'LH_Rest_Voice_IV',
                'LH_Voice_IV_Inserts',
                'LH_Rest_Voice_IV_Inserts',
                'LH_Voice_V',
                'LH_Rest_Voice_V',
                'LH_Voice_V_Inserts',
                'LH_Voice_VI',
                'LH_Rest_Voice_VI',
                'LH_Voice_VI_Inserts',
                'LH_Resonance_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [1, 7],
            ),
        ('duration', "0'23''"),
        (
            'fermata_measure_numbers',
            [4, 6, 9],
            ),
        ('final_measure_is_fermata', True),
        ('final_measure_number', 9),
        ('first_measure_number', 1),
        ('segment_name', '_'),
        ('segment_number', 1),
        ('start_clock_time', "0'00''"),
        ('stop_clock_time', "0'23''"),
        (
            'time_signatures',
            [
                '4/4',
                '2/4',
                '4/4',
                '1/4',
                '4/8',
                '1/4',
                '7/8',
                '16/4',
                '1/4',
                ],
            ),
        ]
    )
