import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Rests',
                'Global_Skips',
                'Music_Context',
                'Piano_Music_Staff_Group',
                'Piano_Music_RH_Staff',
                'RH_Voice_I',
                'RH_Voice_I_Inserts',
                'RH_Voice_II',
                'RH_Voice_II_Inserts',
                'RH_Voice_III',
                'RH_Rest_Voice_III',
                'RH_Voice_III_Inserts',
                'RH_Voice_IV',
                'RH_Rest_Voice_IV',
                'RH_Voice_IV_Inserts',
                'RH_Rest_Voice_IV_Inserts',
                'RH_Voice_V',
                'RH_Voice_VI',
                'RH_Resonance_Voice',
                'Piano_Music_LH_Staff',
                'LH_Voice_I',
                'LH_Voice_II',
                'LH_Voice_III',
                'LH_Voice_IV',
                'LH_Voice_IV_Inserts',
                'LH_Voice_V',
                'LH_Rest_Voice_V',
                'LH_Voice_V_Inserts',
                'LH_Voice_VI',
                'LH_Voice_VI_Inserts',
                'LH_Resonance_Voice',
                'LH_Resonance_Rest_Voice',
                ],
            ),
        (
            'bol_measure_numbers',
            [22, 29, 31],
            ),
        ('duration', "0'24''"),
        (
            'fermata_measure_numbers',
            [23, 25, 28],
            ),
        ('final_measure_number', 33),
        ('first_measure_number', 22),
        ('segment_name', 'B'),
        ('segment_number', 3),
        ('start_clock_time', "0'45''"),
        ('stop_clock_time', "1'09''"),
        (
            'time_signatures',
            [
                '2/4',
                '1/4',
                '5/16',
                '1/4',
                '2/4',
                '5/8',
                '1/4',
                '6/4',
                '21/16',
                '7/4',
                '6/4',
                '4/4',
                ],
            ),
        ]
    )
