import abjad


metadata = abjad.OrderedDict(
    [
        (
            'bol_measure_numbers',
            [
                1,
                3,
                5,
                8,
                9,
                12,
                13,
                16,
                18,
                20,
                23,
                28,
                30,
                31,
                32,
                34,
                36,
                38,
                40,
                42,
                44,
                46,
                48,
                50,
                53,
                57,
                60,
                63,
                66,
                68,
                69,
                71,
                73,
                76,
                78,
                80,
                81,
                83,
                85,
                86,
                87,
                88,
                89,
                90,
                91,
                92,
                93,
                96,
                97,
                99,
                101,
                106,
                ],
            ),
        ('catalog_number_suffix', 'A'),
        ('paper_size', 'arch a'),
        ('price', '$29'),
        ]
    )
