abjad.OrderedDict(
    [
        (
            "bol_measure_numbers",
            [
                1,
                7,
                10,
                13,
                17,
                21,
                29,
                33,
                39,
                47,
                55,
                61,
                68,
                71,
                76,
                78,
                82,
                85,
                87,
                89,
                91,
                93,
                96,
                98,
                103,
            ],
        ),
        ("catalog_number_suffix", "A"),
        ("paper_size", "arch a"),
        ("price", "$29"),
    ]
)
